"""Motion hints for the Echuu live-room frontend.

The frontend owns the actual VRMA asset URLs. The agent sends stable semantic
clip names so the UI can resolve them against its local animation catalog
(vroid / mate-engine / vmagicmirror / sing packs).

Pools are derived from motion_library.json (generated by
echuu-ux-r3f-vite/scripts/build-motion-library.mjs and copied next to this
module). If the library file is missing, legacy hardcoded pools keep working.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

_LIBRARY_PATH = Path(__file__).with_name("motion_library.json")


def _load_usable_clips() -> List[dict]:
    try:
        data = json.loads(_LIBRARY_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    return [c for c in data.get("clips", []) if c.get("usable")]


_CLIPS: List[dict] = _load_usable_clips()


def query_clips(
    categories: Optional[Sequence[str]] = None,
    posture: Optional[str] = None,
    emotion: Optional[str] = None,
    loop: Optional[bool] = None,
    static: Optional[bool] = None,
    tag: Optional[str] = None,
    min_duration: Optional[float] = None,
    max_duration: Optional[float] = None,
    min_energy: Optional[int] = None,
    max_energy: Optional[int] = None,
    packs: Optional[Sequence[str]] = None,
) -> List[dict]:
    """Filter usable library clips by semantic attributes (None duration passes)."""
    out = []
    for c in _CLIPS:
        if categories and c.get("category") not in categories:
            continue
        if posture and c.get("posture") not in (posture, "any"):
            continue
        if emotion and c.get("emotion") != emotion:
            continue
        if loop is not None and bool(c.get("loop")) is not loop:
            continue
        if static is not None and bool(c.get("static")) is not static:
            continue
        if tag and tag not in (c.get("tags") or []):
            continue
        dur = c.get("duration")
        if dur is not None:
            if min_duration is not None and dur < min_duration:
                continue
            if max_duration is not None and dur > max_duration:
                continue
        if min_energy is not None and c.get("energy", 1) < min_energy:
            continue
        if max_energy is not None and c.get("energy", 1) > max_energy:
            continue
        if packs and c.get("pack") not in packs:
            continue
        out.append(c)
    return out


def _names(clips: Iterable[dict]) -> Tuple[str, ...]:
    seen, out = set(), []
    for c in clips:
        name = c.get("name")
        if name and name not in seen:
            seen.add(name)
            out.append(name)
    return tuple(out)


def _pool(fallback: Tuple[str, ...], **query: Any) -> Tuple[str, ...]:
    names = _names(query_clips(**query))
    return names or fallback


# --- Semantic pools (fallbacks = pre-library behaviour) ----------------------
GREET_CLIPS = _pool(
    ("greet_00", "greet_02", "greet_03"),
    categories=("greet",), posture="stand", max_duration=8.0,
)
IDLE_CLIPS = _pool(
    ("Hub_Idle01", "Hub_Idle02", "Hub_Idle03", "Hub_Idle04"),
    categories=("idle",), posture="stand", loop=True, min_duration=3.0, max_duration=20.0,
)
SIT_IDLE_CLIPS = _pool(
    ("shot_sitting",),
    categories=("idle",), posture="sit", loop=True,
)
THINKING_CLIPS = _pool(
    ("spot_gazing_up_2", "WAIT00", "WAIT01"),
    categories=("think",),
)
SPEAKING_CLIPS = _pool(
    ("emote_hey", "elated", "super_delicious"),
    categories=("talk", "react_positive"), max_energy=2, max_duration=8.0, static=False,
)
DANMAKU_CLIPS = _pool(
    ("emote_hey", "finger_gun"),
    categories=("react_positive", "react_surprise"), max_energy=2, max_duration=5.0, static=False,
)
RUPTURE_CLIPS = _pool(
    ("lmao", "determined", "elated"),
    categories=("react_positive",), min_energy=3, max_duration=8.0, static=False,
)
SUCCESS_CLIPS = _pool(("WIN00",), categories=("success",))
DANCE_CLIPS = _pool((), categories=("dance",), min_duration=3.0)
SING_CLIPS = _pool((), categories=("sing",))

# Reaction mode: script emotion -> clip pool (overlay layer on the sitting base).
REACTION_EMOTION_POOLS: Dict[str, Tuple[str, ...]] = {
    "joy": _pool(("elated",), categories=("react_positive",), emotion="happy", max_duration=8.0, static=False),
    "excited": _pool(("yay",), categories=("react_positive",), min_energy=3, max_duration=8.0, static=False),
    "surprised": _pool(("home_tap_w",), categories=("react_surprise",), static=False),
    "frustrated": _pool(("LOSE00",), categories=("react_negative",), max_energy=2, static=False),
    "sad": _pool(("LOSE00",), categories=("react_negative",), emotion="sad", static=False),
    "smug": _pool(("finger_gun", "determined"), categories=("react_positive",), emotion="focused"),
    "shy": _pool(("embar_01",), categories=("react_negative",), emotion="shy", static=False),
}
_REACTION_DEFAULT_POOL = _pool(("emote_hey",), categories=("react_positive",), max_energy=2, static=False)

# cls -> reaction intensity fed to the frontend behaviour state machine.
_CLS_INTENSITY = {
    "NATURAL_CASUAL": 0.35,
    "THEATRICAL": 0.9,
    "HIGH_LOAD": 0.75,
    "HYPER_FLUENT": 0.55,
}


def _pick(clips: Iterable[str], *parts: Any) -> str:
    pool = tuple(clips)
    if not pool:
        raise ValueError("motion clip pool must not be empty")
    key = "|".join(str(part) for part in parts)
    digest = hashlib.sha1(key.encode("utf-8")).digest()
    return pool[int.from_bytes(digest[:4], "big") % len(pool)]


def _motion(state: str, clip: str, *, loop: bool = False, priority: int = 1) -> Dict[str, Any]:
    return {
        "state": state,
        "clip": clip,
        "loop": loop,
        "priority": priority,
    }


def pick_motion_for_step(unit: Any, line: Any, line_in_unit: int = 0) -> Dict[str, Any]:
    """Pick a frontend motion hint for a scripted line event."""
    stage = str(getattr(line, "stage", "") or "").lower()
    axis = str(getattr(unit, "axis", "") or "").lower()
    density = str(getattr(unit, "density", "") or "").lower()
    unit_index = getattr(unit, "index", 0)
    is_rupture = bool(getattr(line, "is_rupture", False))

    if is_rupture:
        return _motion("reacting", _pick(RUPTURE_CLIPS, unit_index, line_in_unit, stage), priority=3)

    if stage in {"intro", "opening", "hook"} and line_in_unit == 0:
        return _motion("greet", _pick(GREET_CLIPS, unit_index, stage), priority=2)

    if stage in {"setup", "think", "thinking", "planning", "pad"} or axis in {"planning", "belief"}:
        return _motion("thinking", _pick(THINKING_CLIPS, unit_index, line_in_unit, density), priority=1)

    if stage in {"listen", "listening", "target"}:
        return _motion("listening", "spot_target_locked", priority=1)

    if stage in {"idle", "wait"}:
        return _motion("idle", _pick(IDLE_CLIPS, unit_index), loop=True, priority=0)

    return _motion("speaking", _pick(SPEAKING_CLIPS, unit_index, line_in_unit, stage, axis), priority=1)


def pick_motion_for_danmaku(unit: Any, danmaku: Any) -> Dict[str, Any]:
    """Pick a short response gesture for an interleaved chat reply."""
    unit_index = getattr(unit, "index", 0)
    text = getattr(danmaku, "text", "")
    user = getattr(danmaku, "user", "")
    return _motion("danmaku", _pick(DANMAKU_CLIPS, unit_index, user, text), priority=2)


def pick_motion_for_reaction(emotion: str, cls: str, *seed_parts: Any) -> Dict[str, Any]:
    """Motion hint + intensity for a reaction-mode step event.

    The frontend keeps the sitting base layer; this hint drives the overlay
    reaction gesture and feeds the behaviour state machine's score.
    """
    pool = REACTION_EMOTION_POOLS.get(str(emotion).lower()) or _REACTION_DEFAULT_POOL
    cls_key = str(cls).upper()
    hint = _motion("reacting", _pick(pool, emotion, cls_key, *seed_parts), priority=2)
    hint["intensity"] = _CLS_INTENSITY.get(cls_key, 0.5)
    return hint


STREAM_START_MOTION = _motion("greet", GREET_CLIPS[0], priority=2)
STREAM_IDLE_MOTION = _motion("idle", IDLE_CLIPS[0], loop=True, priority=0)
STREAM_SUCCESS_MOTION = _motion("success", SUCCESS_CLIPS[0], priority=4)
